/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVeiculosRouteImport } from './routes/app.veiculos'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppPecasRouteImport } from './routes/app.pecas'
import { Route as AppOrdensRouteImport } from './routes/app.ordens'
import { Route as AppFluxoCaixaRouteImport } from './routes/app.fluxo-caixa'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppDespesasRouteImport } from './routes/app.despesas'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppClientesRouteImport } from './routes/app.clientes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosRoute = AppVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppPecasRoute = AppPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensRoute = AppOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDespesasRoute = AppDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/despesas': typeof AppDespesasRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/ordens': typeof AppOrdensRoute
  '/app/pecas': typeof AppPecasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/despesas': typeof AppDespesasRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/ordens': typeof AppOrdensRoute
  '/app/pecas': typeof AppPecasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/despesas': typeof AppDespesasRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/ordens': typeof AppOrdensRoute
  '/app/pecas': typeof AppPecasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/clientes'
    | '/app/crm'
    | '/app/despesas'
    | '/app/equipe'
    | '/app/fluxo-caixa'
    | '/app/ordens'
    | '/app/pecas'
    | '/app/suporte'
    | '/app/veiculos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/clientes'
    | '/app/crm'
    | '/app/despesas'
    | '/app/equipe'
    | '/app/fluxo-caixa'
    | '/app/ordens'
    | '/app/pecas'
    | '/app/suporte'
    | '/app/veiculos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/clientes'
    | '/app/crm'
    | '/app/despesas'
    | '/app/equipe'
    | '/app/fluxo-caixa'
    | '/app/ordens'
    | '/app/pecas'
    | '/app/suporte'
    | '/app/veiculos'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos': {
      id: '/app/veiculos'
      path: '/veiculos'
      fullPath: '/app/veiculos'
      preLoaderRoute: typeof AppVeiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pecas': {
      id: '/app/pecas'
      path: '/pecas'
      fullPath: '/app/pecas'
      preLoaderRoute: typeof AppPecasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ordens': {
      id: '/app/ordens'
      path: '/ordens'
      fullPath: '/app/ordens'
      preLoaderRoute: typeof AppOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fluxo-caixa': {
      id: '/app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/app/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/despesas': {
      id: '/app/despesas'
      path: '/despesas'
      fullPath: '/app/despesas'
      preLoaderRoute: typeof AppDespesasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDespesasRoute: typeof AppDespesasRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppOrdensRoute: typeof AppOrdensRoute
  AppPecasRoute: typeof AppPecasRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppVeiculosRoute: typeof AppVeiculosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppCrmRoute: AppCrmRoute,
  AppDespesasRoute: AppDespesasRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppOrdensRoute: AppOrdensRoute,
  AppPecasRoute: AppPecasRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppVeiculosRoute: AppVeiculosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
